[package]
authors = ["Benno Fünfstück <benno.fuenfstueck@gmail.com>"]
name = "nix-index"
version = "0.1.2"

[[bin]]
doc = false
name = "nix-index"

[[bin]]
name = "nix-locate"

[dependencies]
ansi_term = "0.11.0"
bincode = "0.9.2"
brotli2 = "0.3.2"
byteorder = "1.2.1"
clap = "2.30.0"
error-chain = "0.12.0"
futures = "0.3.5"
grep = "0.1.7"
hyper = "0.13.8"
isatty = "0.1.6"
memchr = "2.0.2"
ordermap = "0.3.4"
regex = "1.0.5"
regex-syntax = "0.4.2"
separator = "0.3.1"
serde = "1.0.27"
serde_bytes = "0.10.3"
serde_derive = "1.0.27"
serde_json = "1.0.32"
stderr = "0.8.0"
tokio = { version = "0.2.22", default-features=false, features=["rt-core","time"]}
tokio-retry = "0.2.0"
void = "1.0.2"
xdg = "2.1.0"
xml-rs = "0.8.0"
xz2 = "0.1.4"
zstd = "0.4.17+zstd.1.3.3"
hyper-proxy = "0.8.0"
url = "2.1.1"
typed-headers = "0.2.0"

[[example]]
name = "nix-index-debug"

[profile]

[profile.release]
debug = true
